from enum import Enum


class BrazilianState(str, Enum):
    """Estados brasileiros."""
    AC = "AC"
    AL = "AL"
    AP = "AP"
    AM = "AM"
    BA = "BA"
    CE = "CE"
    DF = "DF"
    ES = "ES"
    GO = "GO"
    MA = "MA"
    MT = "MT"
    MS = "MS"
    MG = "MG"
    PA = "PA"
    PB = "PB"
    PR = "PR"
    PE = "PE"
    PI = "PI"
    RJ = "RJ"
    RN = "RN"
    RS = "RS"
    RO = "RO"
    RR = "RR"
    SC = "SC"
    SP = "SP"
    SE = "SE"
    TO = "TO"


class AccountType(str, Enum):
    """Tipos de conta bancária."""
    CURRENT = "Corrente"
    SAVINGS = "Poupança"
    BUSINESS = "PJ"


class ProductCategory(str, Enum):
    """Categorias de produtos disponíveis para vendedores."""
    AIR_VENTILATION = "ar e ventilação"
    HANDICRAFT = "artesanato"
    PARTY_SUPPLIES = "artigos para festa"
    AUDIO = "Áudio"
    AUTOMOTIVE = "Automotivo"
    BABY = "Bebê"
    BEAUTY_PERFUMERY = "beleza e perfumaria"
    TOYS = "brinquedos"
    BED_BATH_TABLE = "cama, mesa e banho"
    CAMERAS_DRONES = "câmeras e drones"
    CONSTRUCTION_HOME = "casa de construção"
    SMART_HOME = "casa inteligente"
    CELLPHONES_SMARTPHONES = "celulares e smartphones"
    MATTRESSES = "colchões"
    COMMERCE_INDUSTRY = "comércio e indústria"
    COURSES = "cursos"
    DECORATION = "decoração"
    APPLIANCES = "eletrodomésticos"
    SMALL_APPLIANCES = "eletroportáteis"
    SPORTS_LEISURE = "esporte e lazer"
    TOOLS = "ferramentas"
    MOVIES_SERIES = "filmes e serie"
    HOME_UTILITIES = "utilidades domesticas"
    TV_VIDEO = "tv e vídeo"
    FIXED_TELEPHONY = "telefonia fixa"
    TABLETS_IPADS_EREADER = "tables, ipads e e-reader"
    FOOD_SUPPLEMENTS = "suplementos alimentares"
    SERVICES = "serviços"
    HEALTH_PERSONAL_CARE = "saúde e cuidados pessoais"
    WATCHES = "relógios"
    RELIGION_SPIRITUALITY = "religião e espiritualidade"
    PET_SHOP = "pet shop"
    STATIONERY = "papelaria"
    CHRISTMAS = "natal"
    MUSIC_SHOWS = "musica e shows"
    FURNITURE = "moveis"
    FASHION = "moda"
    MARKET = "mercado"
    BOOKS = "livros"
    MUSICAL_INSTRUMENTS = "instrumentos musicais"
    COMPUTING = "informática"
    GAMES = "games"
    FLOWERS_GARDEN = "flores e jardim"
